// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SudokuSolver.SudokuDb;

namespace TodoApi.Migrations
{
    [DbContext(typeof(SudokuDbContext))]
    [Migration("20211110160102_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SudokuSolver.SudokuDb.Cell", b =>
                {
                    b.Property<int>("row")
                        .HasColumnType("int");

                    b.Property<int>("col")
                        .HasColumnType("int");

                    b.Property<int?>("Tableid")
                        .HasColumnType("int");

                    b.Property<string>("value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("row", "col");

                    b.HasIndex("Tableid");

                    b.ToTable("Cell");

                    b.HasData(
                        new
                        {
                            row = 0,
                            col = 2,
                            value = "1"
                        },
                        new
                        {
                            row = 0,
                            col = 6,
                            value = "7"
                        },
                        new
                        {
                            row = 1,
                            col = 3,
                            value = "4"
                        },
                        new
                        {
                            row = 1,
                            col = 5,
                            value = "8"
                        },
                        new
                        {
                            row = 1,
                            col = 8,
                            value = "3"
                        },
                        new
                        {
                            row = 2,
                            col = 0,
                            value = "3"
                        },
                        new
                        {
                            row = 2,
                            col = 3,
                            value = "9"
                        },
                        new
                        {
                            row = 2,
                            col = 5,
                            value = "6"
                        },
                        new
                        {
                            row = 2,
                            col = 8,
                            value = "1"
                        },
                        new
                        {
                            row = 3,
                            col = 1,
                            value = "2"
                        },
                        new
                        {
                            row = 3,
                            col = 2,
                            value = "8"
                        },
                        new
                        {
                            row = 3,
                            col = 6,
                            value = "1"
                        },
                        new
                        {
                            row = 3,
                            col = 7,
                            value = "5"
                        },
                        new
                        {
                            row = 5,
                            col = 1,
                            value = "5"
                        },
                        new
                        {
                            row = 5,
                            col = 2,
                            value = "4"
                        },
                        new
                        {
                            row = 5,
                            col = 6,
                            value = "6"
                        },
                        new
                        {
                            row = 5,
                            col = 7,
                            value = "3"
                        },
                        new
                        {
                            row = 6,
                            col = 0,
                            value = "1"
                        },
                        new
                        {
                            row = 6,
                            col = 3,
                            value = "3"
                        },
                        new
                        {
                            row = 6,
                            col = 5,
                            value = "4"
                        },
                        new
                        {
                            row = 6,
                            col = 8,
                            value = "9"
                        },
                        new
                        {
                            row = 7,
                            col = 3,
                            value = "1"
                        },
                        new
                        {
                            row = 7,
                            col = 5,
                            value = "9"
                        },
                        new
                        {
                            row = 8,
                            col = 2,
                            value = "2"
                        },
                        new
                        {
                            row = 8,
                            col = 6,
                            value = "3"
                        });
                });

            modelBuilder.Entity("SudokuSolver.SudokuDb.Table", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("SudokuSolver.SudokuDb.Cell", b =>
                {
                    b.HasOne("SudokuSolver.SudokuDb.Table", null)
                        .WithMany("cells")
                        .HasForeignKey("Tableid");
                });

            modelBuilder.Entity("SudokuSolver.SudokuDb.Table", b =>
                {
                    b.Navigation("cells");
                });
#pragma warning restore 612, 618
        }
    }
}
