// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SudokuSolver.SudokuDb;

namespace TodoApi.Migrations
{
    [DbContext(typeof(SudokuDbContext))]
    [Migration("20211111165038_Finished")]
    partial class Finished
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SudokuSolver.Models.Cell", b =>
                {
                    b.Property<int>("row")
                        .HasColumnType("int");

                    b.Property<int>("col")
                        .HasColumnType("int");

                    b.Property<string>("cellValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("row", "col");

                    b.ToTable("Cells");

                    b.HasData(
                        new
                        {
                            row = 0,
                            col = 2,
                            cellValue = "1"
                        },
                        new
                        {
                            row = 0,
                            col = 6,
                            cellValue = "7"
                        },
                        new
                        {
                            row = 1,
                            col = 3,
                            cellValue = "4"
                        },
                        new
                        {
                            row = 1,
                            col = 5,
                            cellValue = "8"
                        },
                        new
                        {
                            row = 1,
                            col = 8,
                            cellValue = "3"
                        },
                        new
                        {
                            row = 2,
                            col = 0,
                            cellValue = "3"
                        },
                        new
                        {
                            row = 2,
                            col = 3,
                            cellValue = "9"
                        },
                        new
                        {
                            row = 2,
                            col = 5,
                            cellValue = "6"
                        },
                        new
                        {
                            row = 2,
                            col = 8,
                            cellValue = "1"
                        },
                        new
                        {
                            row = 3,
                            col = 1,
                            cellValue = "2"
                        },
                        new
                        {
                            row = 3,
                            col = 2,
                            cellValue = "8"
                        },
                        new
                        {
                            row = 3,
                            col = 6,
                            cellValue = "1"
                        },
                        new
                        {
                            row = 3,
                            col = 7,
                            cellValue = "5"
                        },
                        new
                        {
                            row = 5,
                            col = 1,
                            cellValue = "5"
                        },
                        new
                        {
                            row = 5,
                            col = 2,
                            cellValue = "4"
                        },
                        new
                        {
                            row = 5,
                            col = 6,
                            cellValue = "6"
                        },
                        new
                        {
                            row = 5,
                            col = 7,
                            cellValue = "3"
                        },
                        new
                        {
                            row = 6,
                            col = 0,
                            cellValue = "1"
                        },
                        new
                        {
                            row = 6,
                            col = 3,
                            cellValue = "3"
                        },
                        new
                        {
                            row = 6,
                            col = 5,
                            cellValue = "4"
                        },
                        new
                        {
                            row = 6,
                            col = 8,
                            cellValue = "9"
                        },
                        new
                        {
                            row = 7,
                            col = 3,
                            cellValue = "1"
                        },
                        new
                        {
                            row = 7,
                            col = 5,
                            cellValue = "9"
                        },
                        new
                        {
                            row = 8,
                            col = 2,
                            cellValue = "2"
                        },
                        new
                        {
                            row = 8,
                            col = 6,
                            cellValue = "3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
